[plugin]
repository = "https://github.com/Olaren15/ffxiv-status-contrast.git"
commit = "fb35625fe57a2a8fa08c48086ea16c2d533c8cba"
owners = ["Olaren15"]
project_path = "StatusContrast"
changelog = """
- Fix game crash when logging out
"""
