[plugin]
repository = "https://github.com/Olaren15/ffxiv-status-contrast"
commit = "2132ada546815af41f576598a65df51d354ca132"
owners = ["Olaren15"]
project_path = "StatusContrast"
changelog = """
- Initial testing release
"""
