[plugin]
repository = "https://github.com/Olaren15/ffxiv-easy-translate.git"
commit = "45f0e477836ccce7337b27fa161af5b832aeebdb"
owners = ["Olaren15"]
project_path = "EasyTranslate.DalamudPlugin"
changelog = """
- Updated for dawntrail compatibility
"""
